{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "C:\\Users\\jonas\\Documents\\Github\\epymarl\\src",
    "dependencies": [
      "munch==2.5.0",
      "numpy==1.23.1",
      "sacred==0.8.2",
      "torch==2.0.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl_0",
    "repositories": [
      {
        "commit": "03eb2f52be7dcc658e974f77cc451c5d7f9d663d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      },
      {
        "commit": "03eb2f52be7dcc658e974f77cc451c5d7f9d663d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      },
      {
        "commit": "03eb2f52be7dcc658e974f77cc451c5d7f9d663d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources\\main_6edc77b48ae05b7b3bae5b57bf82078a.py"
      ],
      [
        "run.py",
        "_sources\\run_6df4177238aa94b24bef38e04727c0ac.py"
      ],
      [
        "utils\\logging.py",
        "_sources\\logging_19831644a2526c55c2bc12dd75dc94d8.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"C:\\Users\\jonas\\Documents\\Github\\epymarl\\src\\main.py\", line 146, in my_main\n    run(_run, config, _log)\n",
    "  File \"C:\\Users\\jonas\\Documents\\Github\\epymarl\\src\\run.py\", line 60, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"C:\\Users\\jonas\\Documents\\Github\\epymarl\\src\\run.py\", line 192, in run_sequential\n    episode_batch = runner.run(test_mode=False)\n",
    "  File \"C:\\Users\\jonas\\Documents\\Github\\epymarl\\src\\runners\\episode_runner.py\", line 224, in run\n    self.logger.log_heatmaps(heatmaps)\n",
    "  File \"C:\\Users\\jonas\\Documents\\Github\\epymarl\\src\\utils\\logging.py\", line 131, in log_heatmaps\n    background_image = plt.imread(path)\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\matplotlib\\pyplot.py\", line 2195, in imread\n    return matplotlib.image.imread(fname, format)\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\matplotlib\\image.py\", line 1563, in imread\n    with img_open(fname) as image:\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\PIL\\ImageFile.py\", line 105, in __init__\n    self.fp = open(fp, \"rb\")\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jonas\\\\Documents\\\\Github\\\\epymarl\\\\src\\\\utils\\\\logging.py\\\\..\\\\..\\\\..\\\\assets\\\\../assets/bg_bg_line.png'\n"
  ],
  "heartbeat": "2023-09-10T09:17:29.670004",
  "host": {
    "ENV": {},
    "cpu": "Unknown",
    "gpus": {
      "driver_version": "531.79",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 960",
          "persistence_mode": false,
          "total_memory": 2048
        }
      ]
    },
    "hostname": "DESKTOP-1HDPUO6",
    "os": [
      "Windows",
      "Windows-10-10.0.22621-SP0"
    ],
    "python_version": "3.8.16"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2023-09-10T09:08:46.447974",
  "status": "FAILED",
  "stop_time": "2023-09-10T09:17:29.706027"
}